const user = {
  login: "gaearon",
  id: 810438,
  avatar_url: "https://avatars.githubusercontent.com/u/810438?v=3",
  gravatar_id: "",
  url: "https://api.github.com/users/gaearon",
  html_url: "https://github.com/gaearon",
  followers_url: "https://api.github.com/users/gaearon/followers",
  following_url: "https://api.github.com/users/gaearon/following{/other_user}",
  gists_url: "https://api.github.com/users/gaearon/gists{/gist_id}",
  starred_url: "https://api.github.com/users/gaearon/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/gaearon/subscriptions",
  organizations_url: "https://api.github.com/users/gaearon/orgs",
  repos_url: "https://api.github.com/users/gaearon/repos",
  events_url: "https://api.github.com/users/gaearon/events{/privacy}",
  received_events_url: "https://api.github.com/users/gaearon/received_events",
  type: "User",
  site_admin: false,
  name: "Dan Abramov",
  company: "Facebook",
  blog: "http://twitter.com/dan_abramov",
  location: "London, UK",
  email: "dan.abramov@me.com",
  hireable: null,
  bio:
    "Created: Redux, React Hot Loader, React DnD. Now helping make @reactjs better at @facebook.",
  public_repos: 176,
  public_gists: 48,
  followers: 10338,
  following: 171,
  created_at: "2011-05-25T18:18:31Z",
  updated_at: "2016-07-28T14:41:02Z",
};

export { user };
