const user = {
  login: "gaearon",
  id: 810438,
  avatar_url: "https://avatars.githubusercontent.com/u/810438?v=3",
  gravatar_id: "",
  url: "https://api.github.com/users/gaearon",
  html_url: "https://github.com/gaearon",
  followers_url: "https://api.github.com/users/gaearon/followers",
  following_url: "https://api.github.com/users/gaearon/following{/other_user}",
  gists_url: "https://api.github.com/users/gaearon/gists{/gist_id}",
  starred_url: "https://api.github.com/users/gaearon/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/gaearon/subscriptions",
  organizations_url: "https://api.github.com/users/gaearon/orgs",
  repos_url: "https://api.github.com/users/gaearon/repos",
  events_url: "https://api.github.com/users/gaearon/events{/privacy}",
  received_events_url: "https://api.github.com/users/gaearon/received_events",
  type: "User",
  site_admin: false,
  name: "Dan Abramov",
  company: "Facebook",
  blog: "http://twitter.com/dan_abramov",
  location: "London, UK",
  email: "dan.abramov@me.com",
  hireable: null,
  bio:
    "Created: Redux, React Hot Loader, React DnD. Now helping make @reactjs better at @facebook.",
  public_repos: 176,
  public_gists: 48,
  followers: 10338,
  following: 171,
  created_at: "2011-05-25T18:18:31Z",
  updated_at: "2016-07-28T14:41:02Z",
};

const updateUser = {
  login: "TomiHiltunen",
  id: 2010468,
  node_id: "MDQ6VXNlcjIwMTA0Njg=",
  avatar_url: "https://avatars.githubusercontent.com/u/2010468?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/TomiHiltunen",
  html_url: "https://github.com/TomiHiltunen",
  followers_url: "https://api.github.com/users/TomiHiltunen/followers",
  following_url:
    "https://api.github.com/users/TomiHiltunen/following{/other_user}",
  gists_url: "https://api.github.com/users/TomiHiltunen/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/TomiHiltunen/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/TomiHiltunen/subscriptions",
  organizations_url: "https://api.github.com/users/TomiHiltunen/orgs",
  repos_url: "https://api.github.com/users/TomiHiltunen/repos",
  events_url: "https://api.github.com/users/TomiHiltunen/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/TomiHiltunen/received_events",
  type: "User",
  site_admin: false,
};

const followers = [
  {
    login: "TomiHiltunen",
    id: 2010468,
    node_id: "MDQ6VXNlcjIwMTA0Njg=",
    avatar_url: "https://avatars.githubusercontent.com/u/2010468?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/TomiHiltunen",
    html_url: "https://github.com/TomiHiltunen",
    followers_url: "https://api.github.com/users/TomiHiltunen/followers",
    following_url:
      "https://api.github.com/users/TomiHiltunen/following{/other_user}",
    gists_url: "https://api.github.com/users/TomiHiltunen/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/TomiHiltunen/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/TomiHiltunen/subscriptions",
    organizations_url: "https://api.github.com/users/TomiHiltunen/orgs",
    repos_url: "https://api.github.com/users/TomiHiltunen/repos",
    events_url: "https://api.github.com/users/TomiHiltunen/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/TomiHiltunen/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "VamshiKrishnaP",
    id: 5905751,
    node_id: "MDQ6VXNlcjU5MDU3NTE=",
    avatar_url: "https://avatars.githubusercontent.com/u/5905751?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/VamshiKrishnaP",
    html_url: "https://github.com/VamshiKrishnaP",
    followers_url: "https://api.github.com/users/VamshiKrishnaP/followers",
    following_url:
      "https://api.github.com/users/VamshiKrishnaP/following{/other_user}",
    gists_url: "https://api.github.com/users/VamshiKrishnaP/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/VamshiKrishnaP/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/VamshiKrishnaP/subscriptions",
    organizations_url: "https://api.github.com/users/VamshiKrishnaP/orgs",
    repos_url: "https://api.github.com/users/VamshiKrishnaP/repos",
    events_url: "https://api.github.com/users/VamshiKrishnaP/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/VamshiKrishnaP/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "nitrix",
    id: 246380,
    node_id: "MDQ6VXNlcjI0NjM4MA==",
    avatar_url: "https://avatars.githubusercontent.com/u/246380?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/nitrix",
    html_url: "https://github.com/nitrix",
    followers_url: "https://api.github.com/users/nitrix/followers",
    following_url: "https://api.github.com/users/nitrix/following{/other_user}",
    gists_url: "https://api.github.com/users/nitrix/gists{/gist_id}",
    starred_url: "https://api.github.com/users/nitrix/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/nitrix/subscriptions",
    organizations_url: "https://api.github.com/users/nitrix/orgs",
    repos_url: "https://api.github.com/users/nitrix/repos",
    events_url: "https://api.github.com/users/nitrix/events{/privacy}",
    received_events_url: "https://api.github.com/users/nitrix/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "reloweb",
    id: 3200882,
    node_id: "MDQ6VXNlcjMyMDA4ODI=",
    avatar_url: "https://avatars.githubusercontent.com/u/3200882?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/reloweb",
    html_url: "https://github.com/reloweb",
    followers_url: "https://api.github.com/users/reloweb/followers",
    following_url:
      "https://api.github.com/users/reloweb/following{/other_user}",
    gists_url: "https://api.github.com/users/reloweb/gists{/gist_id}",
    starred_url: "https://api.github.com/users/reloweb/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/reloweb/subscriptions",
    organizations_url: "https://api.github.com/users/reloweb/orgs",
    repos_url: "https://api.github.com/users/reloweb/repos",
    events_url: "https://api.github.com/users/reloweb/events{/privacy}",
    received_events_url: "https://api.github.com/users/reloweb/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "harrisrobin",
    id: 3880008,
    node_id: "MDQ6VXNlcjM4ODAwMDg=",
    avatar_url: "https://avatars.githubusercontent.com/u/3880008?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/harrisrobin",
    html_url: "https://github.com/harrisrobin",
    followers_url: "https://api.github.com/users/harrisrobin/followers",
    following_url:
      "https://api.github.com/users/harrisrobin/following{/other_user}",
    gists_url: "https://api.github.com/users/harrisrobin/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/harrisrobin/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/harrisrobin/subscriptions",
    organizations_url: "https://api.github.com/users/harrisrobin/orgs",
    repos_url: "https://api.github.com/users/harrisrobin/repos",
    events_url: "https://api.github.com/users/harrisrobin/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/harrisrobin/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Quirksmode",
    id: 1786608,
    node_id: "MDQ6VXNlcjE3ODY2MDg=",
    avatar_url: "https://avatars.githubusercontent.com/u/1786608?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Quirksmode",
    html_url: "https://github.com/Quirksmode",
    followers_url: "https://api.github.com/users/Quirksmode/followers",
    following_url:
      "https://api.github.com/users/Quirksmode/following{/other_user}",
    gists_url: "https://api.github.com/users/Quirksmode/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Quirksmode/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Quirksmode/subscriptions",
    organizations_url: "https://api.github.com/users/Quirksmode/orgs",
    repos_url: "https://api.github.com/users/Quirksmode/repos",
    events_url: "https://api.github.com/users/Quirksmode/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Quirksmode/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "gabeguz",
    id: 132174,
    node_id: "MDQ6VXNlcjEzMjE3NA==",
    avatar_url: "https://avatars.githubusercontent.com/u/132174?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/gabeguz",
    html_url: "https://github.com/gabeguz",
    followers_url: "https://api.github.com/users/gabeguz/followers",
    following_url:
      "https://api.github.com/users/gabeguz/following{/other_user}",
    gists_url: "https://api.github.com/users/gabeguz/gists{/gist_id}",
    starred_url: "https://api.github.com/users/gabeguz/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/gabeguz/subscriptions",
    organizations_url: "https://api.github.com/users/gabeguz/orgs",
    repos_url: "https://api.github.com/users/gabeguz/repos",
    events_url: "https://api.github.com/users/gabeguz/events{/privacy}",
    received_events_url: "https://api.github.com/users/gabeguz/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ptolts",
    id: 723514,
    node_id: "MDQ6VXNlcjcyMzUxNA==",
    avatar_url: "https://avatars.githubusercontent.com/u/723514?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ptolts",
    html_url: "https://github.com/ptolts",
    followers_url: "https://api.github.com/users/ptolts/followers",
    following_url: "https://api.github.com/users/ptolts/following{/other_user}",
    gists_url: "https://api.github.com/users/ptolts/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ptolts/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ptolts/subscriptions",
    organizations_url: "https://api.github.com/users/ptolts/orgs",
    repos_url: "https://api.github.com/users/ptolts/repos",
    events_url: "https://api.github.com/users/ptolts/events{/privacy}",
    received_events_url: "https://api.github.com/users/ptolts/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "matchartier",
    id: 90409,
    node_id: "MDQ6VXNlcjkwNDA5",
    avatar_url: "https://avatars.githubusercontent.com/u/90409?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/matchartier",
    html_url: "https://github.com/matchartier",
    followers_url: "https://api.github.com/users/matchartier/followers",
    following_url:
      "https://api.github.com/users/matchartier/following{/other_user}",
    gists_url: "https://api.github.com/users/matchartier/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/matchartier/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/matchartier/subscriptions",
    organizations_url: "https://api.github.com/users/matchartier/orgs",
    repos_url: "https://api.github.com/users/matchartier/repos",
    events_url: "https://api.github.com/users/matchartier/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/matchartier/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "saas786",
    id: 1642796,
    node_id: "MDQ6VXNlcjE2NDI3OTY=",
    avatar_url: "https://avatars.githubusercontent.com/u/1642796?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/saas786",
    html_url: "https://github.com/saas786",
    followers_url: "https://api.github.com/users/saas786/followers",
    following_url:
      "https://api.github.com/users/saas786/following{/other_user}",
    gists_url: "https://api.github.com/users/saas786/gists{/gist_id}",
    starred_url: "https://api.github.com/users/saas786/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/saas786/subscriptions",
    organizations_url: "https://api.github.com/users/saas786/orgs",
    repos_url: "https://api.github.com/users/saas786/repos",
    events_url: "https://api.github.com/users/saas786/events{/privacy}",
    received_events_url: "https://api.github.com/users/saas786/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "alicephieu",
    id: 4662539,
    node_id: "MDQ6VXNlcjQ2NjI1Mzk=",
    avatar_url: "https://avatars.githubusercontent.com/u/4662539?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/alicephieu",
    html_url: "https://github.com/alicephieu",
    followers_url: "https://api.github.com/users/alicephieu/followers",
    following_url:
      "https://api.github.com/users/alicephieu/following{/other_user}",
    gists_url: "https://api.github.com/users/alicephieu/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/alicephieu/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/alicephieu/subscriptions",
    organizations_url: "https://api.github.com/users/alicephieu/orgs",
    repos_url: "https://api.github.com/users/alicephieu/repos",
    events_url: "https://api.github.com/users/alicephieu/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/alicephieu/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "maxmx",
    id: 2332621,
    node_id: "MDQ6VXNlcjIzMzI2MjE=",
    avatar_url: "https://avatars.githubusercontent.com/u/2332621?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/maxmx",
    html_url: "https://github.com/maxmx",
    followers_url: "https://api.github.com/users/maxmx/followers",
    following_url: "https://api.github.com/users/maxmx/following{/other_user}",
    gists_url: "https://api.github.com/users/maxmx/gists{/gist_id}",
    starred_url: "https://api.github.com/users/maxmx/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/maxmx/subscriptions",
    organizations_url: "https://api.github.com/users/maxmx/orgs",
    repos_url: "https://api.github.com/users/maxmx/repos",
    events_url: "https://api.github.com/users/maxmx/events{/privacy}",
    received_events_url: "https://api.github.com/users/maxmx/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "julienbrault",
    id: 10821335,
    node_id: "MDQ6VXNlcjEwODIxMzM1",
    avatar_url: "https://avatars.githubusercontent.com/u/10821335?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/julienbrault",
    html_url: "https://github.com/julienbrault",
    followers_url: "https://api.github.com/users/julienbrault/followers",
    following_url:
      "https://api.github.com/users/julienbrault/following{/other_user}",
    gists_url: "https://api.github.com/users/julienbrault/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/julienbrault/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/julienbrault/subscriptions",
    organizations_url: "https://api.github.com/users/julienbrault/orgs",
    repos_url: "https://api.github.com/users/julienbrault/repos",
    events_url: "https://api.github.com/users/julienbrault/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/julienbrault/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "louisval",
    id: 10968247,
    node_id: "MDQ6VXNlcjEwOTY4MjQ3",
    avatar_url: "https://avatars.githubusercontent.com/u/10968247?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/louisval",
    html_url: "https://github.com/louisval",
    followers_url: "https://api.github.com/users/louisval/followers",
    following_url:
      "https://api.github.com/users/louisval/following{/other_user}",
    gists_url: "https://api.github.com/users/louisval/gists{/gist_id}",
    starred_url: "https://api.github.com/users/louisval/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/louisval/subscriptions",
    organizations_url: "https://api.github.com/users/louisval/orgs",
    repos_url: "https://api.github.com/users/louisval/repos",
    events_url: "https://api.github.com/users/louisval/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/louisval/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "roxannemarcil",
    id: 10968235,
    node_id: "MDQ6VXNlcjEwOTY4MjM1",
    avatar_url: "https://avatars.githubusercontent.com/u/10968235?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/roxannemarcil",
    html_url: "https://github.com/roxannemarcil",
    followers_url: "https://api.github.com/users/roxannemarcil/followers",
    following_url:
      "https://api.github.com/users/roxannemarcil/following{/other_user}",
    gists_url: "https://api.github.com/users/roxannemarcil/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/roxannemarcil/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/roxannemarcil/subscriptions",
    organizations_url: "https://api.github.com/users/roxannemarcil/orgs",
    repos_url: "https://api.github.com/users/roxannemarcil/repos",
    events_url: "https://api.github.com/users/roxannemarcil/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/roxannemarcil/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Gabrielle-Ferland",
    id: 10968263,
    node_id: "MDQ6VXNlcjEwOTY4MjYz",
    avatar_url: "https://avatars.githubusercontent.com/u/10968263?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Gabrielle-Ferland",
    html_url: "https://github.com/Gabrielle-Ferland",
    followers_url: "https://api.github.com/users/Gabrielle-Ferland/followers",
    following_url:
      "https://api.github.com/users/Gabrielle-Ferland/following{/other_user}",
    gists_url: "https://api.github.com/users/Gabrielle-Ferland/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Gabrielle-Ferland/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Gabrielle-Ferland/subscriptions",
    organizations_url: "https://api.github.com/users/Gabrielle-Ferland/orgs",
    repos_url: "https://api.github.com/users/Gabrielle-Ferland/repos",
    events_url:
      "https://api.github.com/users/Gabrielle-Ferland/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Gabrielle-Ferland/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jefferyathomas",
    id: 3188050,
    node_id: "MDQ6VXNlcjMxODgwNTA=",
    avatar_url: "https://avatars.githubusercontent.com/u/3188050?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jefferyathomas",
    html_url: "https://github.com/jefferyathomas",
    followers_url: "https://api.github.com/users/jefferyathomas/followers",
    following_url:
      "https://api.github.com/users/jefferyathomas/following{/other_user}",
    gists_url: "https://api.github.com/users/jefferyathomas/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/jefferyathomas/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/jefferyathomas/subscriptions",
    organizations_url: "https://api.github.com/users/jefferyathomas/orgs",
    repos_url: "https://api.github.com/users/jefferyathomas/repos",
    events_url: "https://api.github.com/users/jefferyathomas/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/jefferyathomas/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "chartpath",
    id: 461274,
    node_id: "MDQ6VXNlcjQ2MTI3NA==",
    avatar_url: "https://avatars.githubusercontent.com/u/461274?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/chartpath",
    html_url: "https://github.com/chartpath",
    followers_url: "https://api.github.com/users/chartpath/followers",
    following_url:
      "https://api.github.com/users/chartpath/following{/other_user}",
    gists_url: "https://api.github.com/users/chartpath/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/chartpath/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/chartpath/subscriptions",
    organizations_url: "https://api.github.com/users/chartpath/orgs",
    repos_url: "https://api.github.com/users/chartpath/repos",
    events_url: "https://api.github.com/users/chartpath/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/chartpath/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "nicolejfu",
    id: 13644734,
    node_id: "MDQ6VXNlcjEzNjQ0NzM0",
    avatar_url: "https://avatars.githubusercontent.com/u/13644734?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/nicolejfu",
    html_url: "https://github.com/nicolejfu",
    followers_url: "https://api.github.com/users/nicolejfu/followers",
    following_url:
      "https://api.github.com/users/nicolejfu/following{/other_user}",
    gists_url: "https://api.github.com/users/nicolejfu/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/nicolejfu/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/nicolejfu/subscriptions",
    organizations_url: "https://api.github.com/users/nicolejfu/orgs",
    repos_url: "https://api.github.com/users/nicolejfu/repos",
    events_url: "https://api.github.com/users/nicolejfu/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/nicolejfu/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "moniba",
    id: 8866407,
    node_id: "MDQ6VXNlcjg4NjY0MDc=",
    avatar_url: "https://avatars.githubusercontent.com/u/8866407?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/moniba",
    html_url: "https://github.com/moniba",
    followers_url: "https://api.github.com/users/moniba/followers",
    following_url: "https://api.github.com/users/moniba/following{/other_user}",
    gists_url: "https://api.github.com/users/moniba/gists{/gist_id}",
    starred_url: "https://api.github.com/users/moniba/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/moniba/subscriptions",
    organizations_url: "https://api.github.com/users/moniba/orgs",
    repos_url: "https://api.github.com/users/moniba/repos",
    events_url: "https://api.github.com/users/moniba/events{/privacy}",
    received_events_url: "https://api.github.com/users/moniba/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "robertbrockie",
    id: 124640,
    node_id: "MDQ6VXNlcjEyNDY0MA==",
    avatar_url: "https://avatars.githubusercontent.com/u/124640?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/robertbrockie",
    html_url: "https://github.com/robertbrockie",
    followers_url: "https://api.github.com/users/robertbrockie/followers",
    following_url:
      "https://api.github.com/users/robertbrockie/following{/other_user}",
    gists_url: "https://api.github.com/users/robertbrockie/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/robertbrockie/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/robertbrockie/subscriptions",
    organizations_url: "https://api.github.com/users/robertbrockie/orgs",
    repos_url: "https://api.github.com/users/robertbrockie/repos",
    events_url: "https://api.github.com/users/robertbrockie/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/robertbrockie/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "nk1tz",
    id: 12980165,
    node_id: "MDQ6VXNlcjEyOTgwMTY1",
    avatar_url: "https://avatars.githubusercontent.com/u/12980165?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/nk1tz",
    html_url: "https://github.com/nk1tz",
    followers_url: "https://api.github.com/users/nk1tz/followers",
    following_url: "https://api.github.com/users/nk1tz/following{/other_user}",
    gists_url: "https://api.github.com/users/nk1tz/gists{/gist_id}",
    starred_url: "https://api.github.com/users/nk1tz/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/nk1tz/subscriptions",
    organizations_url: "https://api.github.com/users/nk1tz/orgs",
    repos_url: "https://api.github.com/users/nk1tz/repos",
    events_url: "https://api.github.com/users/nk1tz/events{/privacy}",
    received_events_url: "https://api.github.com/users/nk1tz/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Cathe313",
    id: 12678570,
    node_id: "MDQ6VXNlcjEyNjc4NTcw",
    avatar_url: "https://avatars.githubusercontent.com/u/12678570?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Cathe313",
    html_url: "https://github.com/Cathe313",
    followers_url: "https://api.github.com/users/Cathe313/followers",
    following_url:
      "https://api.github.com/users/Cathe313/following{/other_user}",
    gists_url: "https://api.github.com/users/Cathe313/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Cathe313/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Cathe313/subscriptions",
    organizations_url: "https://api.github.com/users/Cathe313/orgs",
    repos_url: "https://api.github.com/users/Cathe313/repos",
    events_url: "https://api.github.com/users/Cathe313/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Cathe313/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "vntrp",
    id: 12161094,
    node_id: "MDQ6VXNlcjEyMTYxMDk0",
    avatar_url: "https://avatars.githubusercontent.com/u/12161094?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/vntrp",
    html_url: "https://github.com/vntrp",
    followers_url: "https://api.github.com/users/vntrp/followers",
    following_url: "https://api.github.com/users/vntrp/following{/other_user}",
    gists_url: "https://api.github.com/users/vntrp/gists{/gist_id}",
    starred_url: "https://api.github.com/users/vntrp/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/vntrp/subscriptions",
    organizations_url: "https://api.github.com/users/vntrp/orgs",
    repos_url: "https://api.github.com/users/vntrp/repos",
    events_url: "https://api.github.com/users/vntrp/events{/privacy}",
    received_events_url: "https://api.github.com/users/vntrp/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "FrancoisLeclerc",
    id: 12959187,
    node_id: "MDQ6VXNlcjEyOTU5MTg3",
    avatar_url: "https://avatars.githubusercontent.com/u/12959187?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/FrancoisLeclerc",
    html_url: "https://github.com/FrancoisLeclerc",
    followers_url: "https://api.github.com/users/FrancoisLeclerc/followers",
    following_url:
      "https://api.github.com/users/FrancoisLeclerc/following{/other_user}",
    gists_url: "https://api.github.com/users/FrancoisLeclerc/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/FrancoisLeclerc/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/FrancoisLeclerc/subscriptions",
    organizations_url: "https://api.github.com/users/FrancoisLeclerc/orgs",
    repos_url: "https://api.github.com/users/FrancoisLeclerc/repos",
    events_url: "https://api.github.com/users/FrancoisLeclerc/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/FrancoisLeclerc/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "noratop",
    id: 9258865,
    node_id: "MDQ6VXNlcjkyNTg4NjU=",
    avatar_url: "https://avatars.githubusercontent.com/u/9258865?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/noratop",
    html_url: "https://github.com/noratop",
    followers_url: "https://api.github.com/users/noratop/followers",
    following_url:
      "https://api.github.com/users/noratop/following{/other_user}",
    gists_url: "https://api.github.com/users/noratop/gists{/gist_id}",
    starred_url: "https://api.github.com/users/noratop/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/noratop/subscriptions",
    organizations_url: "https://api.github.com/users/noratop/orgs",
    repos_url: "https://api.github.com/users/noratop/repos",
    events_url: "https://api.github.com/users/noratop/events{/privacy}",
    received_events_url: "https://api.github.com/users/noratop/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "krysits",
    id: 1294305,
    node_id: "MDQ6VXNlcjEyOTQzMDU=",
    avatar_url: "https://avatars.githubusercontent.com/u/1294305?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/krysits",
    html_url: "https://github.com/krysits",
    followers_url: "https://api.github.com/users/krysits/followers",
    following_url:
      "https://api.github.com/users/krysits/following{/other_user}",
    gists_url: "https://api.github.com/users/krysits/gists{/gist_id}",
    starred_url: "https://api.github.com/users/krysits/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/krysits/subscriptions",
    organizations_url: "https://api.github.com/users/krysits/orgs",
    repos_url: "https://api.github.com/users/krysits/repos",
    events_url: "https://api.github.com/users/krysits/events{/privacy}",
    received_events_url: "https://api.github.com/users/krysits/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "colino",
    id: 4049806,
    node_id: "MDQ6VXNlcjQwNDk4MDY=",
    avatar_url: "https://avatars.githubusercontent.com/u/4049806?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/colino",
    html_url: "https://github.com/colino",
    followers_url: "https://api.github.com/users/colino/followers",
    following_url: "https://api.github.com/users/colino/following{/other_user}",
    gists_url: "https://api.github.com/users/colino/gists{/gist_id}",
    starred_url: "https://api.github.com/users/colino/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/colino/subscriptions",
    organizations_url: "https://api.github.com/users/colino/orgs",
    repos_url: "https://api.github.com/users/colino/repos",
    events_url: "https://api.github.com/users/colino/events{/privacy}",
    received_events_url: "https://api.github.com/users/colino/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "spasiu",
    id: 2235885,
    node_id: "MDQ6VXNlcjIyMzU4ODU=",
    avatar_url: "https://avatars.githubusercontent.com/u/2235885?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/spasiu",
    html_url: "https://github.com/spasiu",
    followers_url: "https://api.github.com/users/spasiu/followers",
    following_url: "https://api.github.com/users/spasiu/following{/other_user}",
    gists_url: "https://api.github.com/users/spasiu/gists{/gist_id}",
    starred_url: "https://api.github.com/users/spasiu/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/spasiu/subscriptions",
    organizations_url: "https://api.github.com/users/spasiu/orgs",
    repos_url: "https://api.github.com/users/spasiu/repos",
    events_url: "https://api.github.com/users/spasiu/events{/privacy}",
    received_events_url: "https://api.github.com/users/spasiu/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "dcodus",
    id: 12925816,
    node_id: "MDQ6VXNlcjEyOTI1ODE2",
    avatar_url: "https://avatars.githubusercontent.com/u/12925816?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dcodus",
    html_url: "https://github.com/dcodus",
    followers_url: "https://api.github.com/users/dcodus/followers",
    following_url: "https://api.github.com/users/dcodus/following{/other_user}",
    gists_url: "https://api.github.com/users/dcodus/gists{/gist_id}",
    starred_url: "https://api.github.com/users/dcodus/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/dcodus/subscriptions",
    organizations_url: "https://api.github.com/users/dcodus/orgs",
    repos_url: "https://api.github.com/users/dcodus/repos",
    events_url: "https://api.github.com/users/dcodus/events{/privacy}",
    received_events_url: "https://api.github.com/users/dcodus/received_events",
    type: "User",
    site_admin: false,
  },
];

export { user, followers, updateUser };
