const SET_SEARCH_TERM = "SET_SEARCH_TERM";
const LOADING_PENDING = "LOADING_PENDING";
const LOADING_SUCCESS = "LOADING_SUCCESS";
const LOADING_FAILED = "LOADING_FAILED";
const FETCH_USERS_PENDING = "FETCH_USERS_PENDING";
const FETCH_USERSS_SUCCESS = "FETCH_USERSS_SUCCESS";
const FETCH_USERSS_FAILED = "FETCH_USERSS_FAILED";
const SET_SEARCH_USER = "SET_SEARCH_USER";
const CLEAR_USER = "CLEAR_USER";
const SET_USER_REPOS = "SET_USER_REPOS";
const CLEAR_USER_REPOS = "CLEAR_USER_REPOS";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const CLEAR_PAGINATION = "CLEAR_PAGINATION";
const SET_USER_FOLLOWING = "SET_USER_FOLLOWING";
const CLEAR_USER_FOLLOWING = "CLEAR_USER_FOLLOWING";
const SET_USER_FOLLOWERS = "SET_USER_FOLLOWERS";
const CLEAR_USER_FOLLOWERS = "SET_USER_FOLLOWERS";
export {
  SET_SEARCH_TERM,
  LOADING_PENDING,
  LOADING_SUCCESS,
  LOADING_FAILED,
  FETCH_USERS_PENDING,
  FETCH_USERSS_SUCCESS,
  FETCH_USERSS_FAILED,
  SET_SEARCH_USER,
  CLEAR_USER,
  SET_USER_REPOS,
  CLEAR_USER_REPOS,
  SET_CURRENT_PAGE,
  CLEAR_PAGINATION,
  SET_USER_FOLLOWING,
  CLEAR_USER_FOLLOWING,
  SET_USER_FOLLOWERS,
  CLEAR_USER_FOLLOWERS,
};
