const SET_SEARCH_TERM = "SET_SEARCH_TERM";
const FETCH_USER_PENDING = "FETCH_USER_PENDING";
const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
const FETCH_USER_FAILED = "FETCH_USER_FAILED";
const FETCH_USERS_PENDING = "FETCH_USERS_PENDING";
const FETCH_USERSS_SUCCESS = "FETCH_USERSS_SUCCESS";
const FETCH_USERSS_FAILED = "FETCH_USERSS_FAILED";
export {
  SET_SEARCH_TERM,
  FETCH_USER_PENDING,
  FETCH_USER_SUCCESS,
  FETCH_USER_FAILED,
  FETCH_USERS_PENDING,
  FETCH_USERSS_SUCCESS,
  FETCH_USERSS_FAILED,
};
